name: Build

on:
  workflow_dispatch:
    inputs:
      qt_version:
        default: '6.8.0'
        required: true
        type: string
        description: 'qt_version'
      qt_arch:
        default: 'win64_mingw'
        required: true
        type: string
        description: 'qt_arch'
      qt_tools:
        default: 'tools_mingw1310'
        required: true
        type: string
        description: 'qt_tools'


jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          host: 'windows'
          target: 'desktop'
          version: ${{ inputs.qt_version }}
          arch: ${{ inputs.qt_arch }}
          tools: ${{ inputs.qt_tools }}

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1

      - name: Checkout & Build
        run: |
          git clone --recursive https://github.com/stdware/qwindowkit -G "MinGW Makefiles"
          cd qwindowkit
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=D:/qwindowkit
          cmake --build build --target install --config Debug
          cmake --build build --target install --config Release
