name: Static Build

on:
  workflow_dispatch:
    inputs:
      qt_version:
        default: 'Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527'
        required: true
        type: choice
        description: 'qt_version'
        options:
          - Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104
          - Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104
          - Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104
          - Qt5.15.14-Windows-x86-MinGW8.1.0-staticFull-20240527
          - Qt5.15.14-Windows-x86_64-MinGW8.1.0-staticFull-20240527
          - Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Qt Static
        uses: orestonce/install-qt@main
        with:
          version: ${{ inputs.qt_version }}
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1

      - name: Checkout & Build
        run: |
          git clone --recursive https://github.com/stdware/qwindowkit
          cd qwindowkit
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=D:/qwindowkit -DQWINDOWKIT_BUILD_STATIC=TRUE -G "MinGW Makefiles"
          cmake --build build --target install --config Release

      - name: Package ZIP
        uses: actions/upload-artifact@v4
        with:
          name: qwindowkit
          path: |
            D:/qwindowkit/**
          overwrite: true
          compression-level: 9
