name: Build PDF4QT

on:
  workflow_dispatch:
    inputs:
      qt_version:
        default: '6.8.0'
        required: true
        type: string
        description: 'qt_version'
      qt_arch:
        default: 'win64_mingw'
        required: true
        type: string
        description: 'qt_arch'
      qt_tools:
        default: 'tools_cmake tools_mingw1310 tools_ninja'
        required: true
        type: string
        description: 'qt_tools'


jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && bootstrap-vcpkg.bat
          set "VCPKG_ROOT=D:\a\build_qwindowkit\build_qwindowkit\vcpkg"
          set PATH=%VCPKG_ROOT%;%PATH%

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          host: 'windows'
          target: 'desktop'
          version: ${{ inputs.qt_version }}
          arch: ${{ inputs.qt_arch }}
          tools: ${{ inputs.qt_tools }}

      - name: Checkout & Build
        run: |
          git clone https://github.com/JakubMelka/PDF4QT
          cd PDF4QT
          cmake -B build -S . -DPDF4QT_INSTALL_QT_DEPENDENCIES=0 -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX='D:/p4q' -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake --install build

      - name: Package ZIP
        uses: actions/upload-artifact@v4
        with:
          name: qwindowkit
          path: |
            D:/p4q/**
          overwrite: true
          compression-level: 9
