name: Build qt-static

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: AllanChain/install-qt-static@v6.8.2-1

      - name: Checkout & Build
        run: |
          git clone --recursive https://github.com/stdware/qwindowkit
          cd qwindowkit
          qt-cmake .
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=D:/qwindowkit -DQWINDOWKIT_BUILD_STATIC=TRUE -G "Visual Studio 17 2022"
          cmake --build build --target install --config Release

      - name: Package ZIP
        uses: actions/upload-artifact@v4
        with:
          name: qwindowkit
          path: |
            D:/qwindowkit/**
          overwrite: true
          compression-level: 9
          retention-days: 3
